# Generated by Django 4.0.2 on 2022-03-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=32)),
                ('creator', models.CharField(max_length=20)),
                ('noOfTeamMembers', models.IntegerField()),
                ('priority', models.CharField(choices=[('H', 'High'), ('Medium', 'Medium'), ('L', 'Low')], max_length=6)),
                ('typeOfProject', models.CharField(max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
