# Generated by Django 4.0.2 on 2022-03-03 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=32)),
                ('assigned_to', models.CharField(max_length=20)),
                ('priority', models.CharField(choices=[('H', 'High'), ('Medium', 'Medium'), ('L', 'Low')], max_length=6)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.project')),
            ],
        ),
    ]
