# Generated by Django 4.0.2 on 2022-03-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_issue_label_issue_status_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='label',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('D', 'Done'), ('O', 'Ongoing')], max_length=7),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.CharField(max_length=32),
        ),
    ]
