# Generated by Django 4.0.2 on 2022-03-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_alter_issue_label_alter_issue_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('I', 'InProgress'), ('C', 'Closed')], max_length=7),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.CharField(choices=[('S', 'Story'), ('T', 'Task'), ('B', 'Bug')], max_length=5),
        ),
    ]
