# Generated by Django 4.0.2 on 2022-03-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_alter_issue_status_alter_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(default=2, max_length=32),
            preserve_default=False,
        ),
    ]
